
export const USER_INFO = [
        {
            "id": 1,
            "name": "Leanne Graham",
            "username": "Bret",
            "email": "Sincere@april.biz",
            "empId": "E0556",
            "jobTitle": "Business Analyst",
            "department": "Delivery",
            "reportingTo": "Alfred Hitcock",
            "phone": "(770)-736-8031",
            "imgURl": "https://robohash.org/Terry.png?set=set4",
        },
        {
            "id": 2,
            "name": "Ervin Howell",
            "username": "Antonette",
            "email": "Shanna@melissa.tv",
            "empId": "E0126",
            "jobTitle": "Data Scientist",
            "department": "Delivery",
            "reportingTo": "Daniel Rodriguez",
            "imgURl": "https://robohash.org/Sheldon.png?set=set4",
            "phone": "(010)-692-6593",
        },
        {
            "id": 3,
            "name": "Clementine Bauch",
            "username": "Samantha",
            "email": "Nathan@yesenia.net",
            "empId": "E0852",
            "jobTitle": "Cloud Architect",
            "department": "Delivery",
            "reportingTo": "Sophia Patel",
            "imgURl": "https://robohash.org/Terrill.png?set=set4",
            "phone": "(463)-123-4447",
        },
        {
            "id": 4,
            "name": "Patricia Lebsack",
            "username": "Karianne",
            "email": "Julianne.OConner@kory.org",
            "empId": "E0111",
            "jobTitle": "UI/UX Designer",
            "department": "Delivery",
            "reportingTo": "Daniel Rodriguez",
            "imgURl": "https://robohash.org/Miles.png?set=set4",
            "phone": "(493)-170-9623"
        },
        {
            "id": 5,
            "name": "Chelsey Dietrich",
            "username": "Kamren",
            "email": "Lucio_Hettinger@annie.ca",
            "empId": "E0285",
            "jobTitle": "Data Scientist",
            "department": "Delivery",
            "reportingTo": "Daniel Rodriguez",
            "imgURl": "https://robohash.org/Mavis.png?set=set4",
            "phone": "(254)-954-1289",
        },
        {
            "id": 6,
            "name": "Mrs. Dennis Schulist",
            "username": "Leopoldo_Corkery",
            "email": "Karley_Dach@jasper.info",
            "empId": "E0235",
            "jobTitle": "Network Engineer",
            "department": "Delivery",
            "reportingTo": "Sophia Patel",
            "imgURl": "https://robohash.org/Alison.png?set=set4",
            "phone": "(477)-935-8478"
        },
        {
            "id": 7,
            "name": "Kurtis Weissnat",
            "username": "Elwyn.Skiles",
            "email": "Telly.Hoeger@billy.biz",
            "empId": "E0921",
            "jobTitle": "Business Analyst",
            "department": "Delivery",
            "reportingTo": "Alfred Hitcock",
            "imgURl": "https://robohash.org/Oleta.png?set=set4",
            "phone": "(210)-067-6132"
        },
        {
            "id": 8,
            "name": "Nicholas Runolfsdottir V",
            "username": "Maxime_Nienow",
            "email": "Sherwood@rosamond.me",
            "empId": "E0120",
            "jobTitle": "Network Engineer",
            "department": "Delivery",
            "reportingTo": "Daniel Rodriguez",
            "imgURl": "https://robohash.org/Ewell.png?set=set4",
            "phone": "(586)-493-6943"
        }
]